<?php

$lang = array(
    // Gestion des exceptions lancées par CoreSecure
    'ERROR_CODE_0' => 'Erreur interne inconnue.',
    'ERROR_CODE_1' => 'Le type de droit \'%1$s\' est inconnu.',
    'ERROR_CODE_2' => 'Le pilote \'%1$s\' n\'est pas encore supporté.',
    'ERROR_CODE_3' => 'L\'implémentation du pilote \'%1$s\' n\'est pas utilisable.',
    'ERROR_CODE_4' => 'Une erreur lors du chargement d\'un fichier est survenue.',
    'ERROR_CODE_5' => 'Impossible de charger le fichier de configuration du cache.',
    'ERROR_CODE_6' => 'Impossible de charger le fichier de la base de données.',
    'ERROR_CODE_7' => 'Impossible de charger le fichier du site.',
    'ERROR_CODE_8' => 'Le site est actuellement fermé.',
    'ERROR_CODE_9' => 'La méthode \'%1$s\' utlisée pour la requête vers le protocole HTTP n\'est pas valide.',
    'ERROR_CODE_10' => 'Vous devez utiliser l\'index du site pour naviguer correctement.',
    'ERROR_CODE_11' => 'Les données reçues sont potentiellement dangereuses.',
    'ERROR_CODE_12' => 'La requête n\'est pas valide.',
    'ERROR_CODE_13' => 'Aucune connexion disponible pour la transaction.',
    'ERROR_CODE_14' => 'LIBRE',
    'ERROR_CODE_15' => 'L\'entité \'%1$s\' n\'a pas été trouvée.',
    'ERROR_CODE_16' => 'La position de block \'%1$s\' n\'est pas valide.',
    'ERROR_CODE_17' => 'Une erreur est survenue lors de la lecture d\'un template.',
    'ERROR_CODE_18' => 'La configuration des templates n\'est pas valide.',
    'ERROR_CODE_19' => 'Une erreur SQL est survenue lors d\'une requête.',
    'ERROR_CODE_20' => 'Erreur de connexion lors de la création d\'une transaction.',
    'ERROR_CODE_21' => 'Erreur lors de la sélection du noeud de données pour la transaction.',
    'ERROR_CODE_22' => 'Une dépendance nécessaire à la transaction n\'est pas disponible.',
    'ERROR_CODE_23' => 'Le fichier d\'un module n\'a pas été trouvé.',
    'ERROR_CODE_24' => 'L\'implémentation du module \'%1$s\' n\'est pas utilisable.',
    'ERROR_CODE_25' => 'L\'implémentation du block \'%1$s\' n\'est pas utilisable.',
    'ERROR_CODE_26' => 'Le fichier d\'un block n\'a pas été trouvé.',
// Erreur diverse (qui ne sont pas des exceptions)
    'ERROR_404' => 'Erreur 404, la page demandée est introuvable.',
    'ERROR_SESSION_COOKIE' => 'Impossible d\'ouvrir une session, vérifiez vos paramètres cookie.',
// Chemin par défaut
    'TRAIL_DISPLAY' => 'Accueil',
// Administration
    'ADMIN_RIGHT_ALL' => 'Tous droits et actions de modérations et d\'administration du site, sans limitation.',
    'ADMIN_RIGHT_MODULE' => 'Droit concernant la visualisation et/ou la modération du module',
    'ADMIN_RIGHT_BLOCK' => 'Droit concernant la visualisation et/ou la modération du block',
    'ADMIN_RIGHT_PAGE' => 'Droit concernant la visualisation et/ou la modération de la page',
// Erreur d'accès, droits insuffisants
    'ERROR_ACCES_ZONE' => 'Désolé, mais il n\'y pas possible de continuer.',
    'ERROR_ACCES_OFF' => 'L\'accès à cette page a été desactivé.',
    'ERROR_ACCES_MEMBER' => 'Pour consulter cette page, il est nécessaire d\'être un membre du site.',
    'ERROR_ACCES_ADMIN' => 'Vous ne possedez pas les droits suffisants pour afficher cette page.',
    'ERROR_ACCES_FORBIDDEN' => 'Vous n\'avez pas l\'autorisation d\'afficher cette page.',
// Date
    'JANUARY' => 'Janvier',
    'FEBRUARY' => 'Février',
    'MARCH' => 'Mars',
    'APRIL' => 'Avril',
    'MAY' => 'Mai',
    'JUNE' => 'Juin',
    'JULY' => 'Juillet',
    'AUGUST' => 'Août',
    'SEPTEMBER' => 'Septembre',
    'OCTOBER' => 'Octobre',
    'NOVEMBER' => 'Novembre',
    'DECEMBER' => 'Décembre', /*
      'DATE' => 'Date',
      'DAYS' => 'jours',
      'HOURS' => 'heures',
      'MINUTES' => 'minutes',
      'SECONDS' => 'secondes', */

// Captcha
    'CAPTCHA_MAKE_LETTER' => 'Écrivez la lettre de l\'alphabet correspondant au chiffre',
    'CAPTCHA_MAKE_LETTERS' => 'Écrivez les premières lettres de l\'alphabet jusqu\'a',
    'CAPTCHA_MAKE_NUMBER_TO_MONTH' => 'Écrivez le mois correspondant chiffre',
    'CAPTCHA_MAKE_MONTH_TO_NUMBER' => 'Écrivez le chiffre correspondant au mois de',
    'CAPTCHA_MAKE_NUMBERS' => 'En partant du chiffre 0, écrivez jusqu\'au chiffre',
    'CAPTCHA_MAKE_PICTURE_CODE' => 'Recopiez le code de l\'image',
    'CAPTCHA_MAKE_SIMPLE_CALCULATION' => 'Calculez l\'opération suivante',
    'CAPTCHA_INVALID' => 'Le code de sécurité que vous avez entré n\'est pas valide',
// Orientation
    'LEFT' => 'Gauche',
    'RIGHT' => 'Droite',
    'TOP' => 'Haut',
    'BOTTOM' => 'Bas',
    'MODULETOP' => 'En haut du module',
    'MODULEBOTTOM' => 'En bas du module',
// Accessibilité
    'ACCESS_NONE' => 'Désactivé',
    'ACCESS_PUBLIC' => 'Public',
    'ACCESS_REGISTRED' => 'Membre',
    'ACCESS_ADMIN' => 'Administrateur',
    'ACCESS_SPECIFIC_RIGHT' => 'Administrateur avec droit',
// Divers
    'WELCOME' => 'Bienvenue',
    'EMAIL' => 'Votre adresse email',
    'LOGIN' => 'Votre identifiant',
    'PASSWORD' => 'Votre mot de passe',
    'VALID' => 'Valider',
    'DATA_SAVED' => 'Les informations ont été correctement sauvegardé.',
    'DATA_INVALID' => 'Les informations comportent des éléments invalides.',
    'DATA_DELETED' => 'Les informations ont été correctement supprimé.'
);
